# This is a basic workflow to help you get started with Actions

name: Deploy MultiDocker

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "master" branch
  push:
    branches: ["master", "main"]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Login to Docker
        run: docker login -u ${{ secrets.DOCKER.DOCKER_USERNAME }} -p ${{ secrets.DOCKER.DOCKER_PASSWORD }}

      - name: Build frontend Image and run test
        run: |
          docker build -t adiaditiwri/react-test -f ./client/Dockerfile.dev ./client,
          docker run -e CI=true adiaditiwri/react-test npm test

      - name: Building all image
        run: |
          docker build -t adiaditiwri/multi-client ./client,
          docker build -t adiaditiwri/multi-nginx ./nginx,
          docker build -t adiaditiwri/multi-server ./server,
          docker build -t adiaditiwri/multi-worker ./worker

      - name: Pushing all the image
        run: |
          docker push adiaditiwri/multi-client,
          docker push adiaditiwri/multi-nginx,
          docker push adiaditiwri/multi-server,
          docker push adiaditiwri/multi-worker

      # - name: Generate deployment package
      #   run: zip -r deploy.zip . -x '*.git*'

      # - name: Deploy to EB
      #   uses: einaregilsson/beanstalk-deploy@v18
      #   with:
      #     aws_access_key: ${{ secrets.AWS.AWS_ACCESS_KEY }}
      #     aws_secret_key: ${{ secrets.AWS.AWS_SECRET_KEY }}
      #     application_name: multi-gh
      #     environment_name: Multigh-env
      #     existing_bucket_name: elasticbeanstalk-us-east-1-923445559289
      #     region: ap-south-1
      #     version_label: ${{ github.sha }}
      #     deployment_package: deploy.zip
